<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>

        <RootNamespace>TestSourceGenerators</RootNamespace>
        <PackageId>TestSourceGenerators</PackageId>
    </PropertyGroup>

<!--    <ItemGroup>-->
<!--        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">-->
<!--            <PrivateAssets>all</PrivateAssets>-->
<!--            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
<!--        </PackageReference>-->
<!--        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0"/>-->
<!--        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.3.0"/>-->
<!--    </ItemGroup>-->
    
    <ItemGroup>
        <Analyzer Include="..\..\Sun.SourceGenerator\bin\Debug\netstandard2.0\Sun.SourceGenerator.dll" />
        <Analyzer Include="..\..\Sun.SourceGenerator.RC\bin\Debug\netstandard2.0\Sun.SourceGenerator.RC.dll" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Sun.SourceGenerator\Sun.SourceGenerator.csproj" />
      <ProjectReference Include="..\..\Sun.SourceGenerator.RC\Sun.SourceGenerator.RC.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="UnityEngine">
        <HintPath>..\..\..\..\..\..\..\Applications\Unity\Hub\Editor\2021.3.42f1\Unity.app\Contents\Managed\UnityEngine.dll</HintPath>
      </Reference>
    </ItemGroup>


</Project>
