<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>TestSourceGenerators.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\TestSourceGenerators\TestSourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="DDD.UbiquitousLanguageRegistry.txt"/>
        <AdditionalFiles Include="DDD.UbiquitousLanguageRegistry.txt"/>
    </ItemGroup>

</Project>
